using System;
using System.Numerics;

namespace CFDSharpClassLibrary.PotentialFlow
{
    /// <summary>
    /// A class containing functions for computing quantities related to velocity.
    /// </summary>
    public static class Velocity
    {
        /// <summary>
        /// Computes the steady state velocity at r generated by the point source.
        /// </summary>
        /// <param name="r">The point at which the velocity is to be computed.</param>
        /// <param name="pointSource">The point source causing the velocity.</param>
        /// <returns>The velocity at the point r.</returns>
        public static Vector3 ComputeSteadyState(Vector3 r, IPointSource pointSource)
        {
            Vector3 dr = r - pointSource.Position; // A vector pointing from the point source to r
            Vector3 velocityPotential = 
                (float)(pointSource.Strength / (4 * Math.PI * dr.LengthSquared())) * dr;
            return velocityPotential;
        }
        /// <summary>
        /// Computes the steady state velocity at r generated by the point sources.
        /// </summary>
        /// <param name="r">The point at which the velocity potential is to be computed.</param>
        /// <param name="pointSources">The point sources causing the velocity.</param>
        /// <returns>The velocity at the point r.</returns>
        public static Vector3 ComputeSteadyState(Vector3 r, IPointSource[] pointSources)
        {
            Vector3 velocityPotential = Vector3.Zero;
            for (int i = 0; i < pointSources.Length; i++)
            {
                velocityPotential += ComputeSteadyState(r, pointSources[i]);
            }
            return velocityPotential;
        }
    }
}
